-- 8.2 live core schema. Review the target project and SQL before execution.

create schema if not exists finance;

revoke all on schema finance from public;
revoke all on schema finance from anon, authenticated, service_role;

create table if not exists finance.symbols (
  symbol text primary key check (symbol ~ '^[0-9]{6}$'),
  name text not null,
  market text not null default 'KRX',
  note text,
  created_at timestamptz not null default now()
);

create table if not exists finance.daily_prices (
  symbol text not null references finance.symbols(symbol),
  trade_date date not null,
  open_price bigint not null check (open_price >= 0),
  high_price bigint not null check (high_price >= 0),
  low_price bigint not null check (low_price >= 0),
  close_price bigint not null check (close_price >= 0),
  volume bigint check (volume >= 0),
  source text not null default 'kiwoom',
  adjusted boolean not null default true,
  primary key (symbol, trade_date),
  check (high_price >= greatest(open_price, low_price, close_price)),
  check (low_price <= least(open_price, high_price, close_price))
);

create table if not exists finance.positions (
  symbol text not null references finance.symbols(symbol),
  as_of_date date not null,
  quantity integer not null check (quantity >= 0),
  avg_price numeric not null check (avg_price >= 0),
  primary key (symbol, as_of_date)
);

create table if not exists finance.orders (
  id bigint generated by default as identity primary key,
  symbol text not null references finance.symbols(symbol),
  side text not null check (side in ('BUY', 'SELL')),
  quantity integer not null check (quantity > 0),
  order_type text not null default 'MARKET' check (order_type in ('MARKET', 'LIMIT')),
  limit_price bigint check (limit_price >= 0),
  status text not null default 'drafted'
    check (status in ('drafted', 'approved', 'executed', 'rejected', 'unknown', 'canceled')),
  broker_order_no text,
  is_dry_run boolean not null default false,
  rationale text,
  drafted_at timestamptz not null default now(),
  approved_at timestamptz,
  executed_at timestamptz
);

create index if not exists daily_prices_trade_date_idx
  on finance.daily_prices (trade_date desc);

alter table finance.symbols enable row level security;
alter table finance.daily_prices enable row level security;
alter table finance.positions enable row level security;
alter table finance.orders enable row level security;

revoke all privileges on all tables in schema finance
  from public, anon, authenticated, service_role;
revoke all privileges on all sequences in schema finance
  from public, anon, authenticated, service_role;
